name: "Test Linux"

on:
  workflow_call:

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ github.head_ref }}
      fetch-depth: 0

  - name: Download Build Artifact
    uses: actions/download-artifact@v4
    with:
      name: ${{ env.buildArtifactName }}
      path: ${{ env.buildFolderName }}

  - name: Run Tests
    shell: pwsh
    run: ./build.ps1 -tasks test

  - name: Publish Test Artifact
    uses: actions/upload-artifact@v4
    with:
      path: ${{ env.buildFolderName }}/${{ env.testResultFolderName }}/
      name: CodeCoverage{{ runner.os }}
    if: success() || failure()
